name: laptop_price_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - pandas
      - scikit-learn
      - numpy
      - matplotlib
      - mlflow==2.19.0
      - dagshub
