name: laptop_price_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    # Wajib: Library untuk model dan tracking
    - pandas
    - scikit-learn
    - numpy
    - matplotlib
    - mlflow
    - dagshub